version: '2'
services:
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "application_db"

  application:
    image: app/hibernate
    ports:
      - "8080:8080"
    environment: #intrduce secrets
      DB_URL: "jdbc:postgresql://database:5432/application_db"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"